name: Scrape ATL TSA wait times

on:
  schedule:
    # Every 10 minutes; you can change to */5 for every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write  # allow committing back to the repo

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scrape.py

      # Commit the updated CSV back to the repo only if it changed
      - name: Commit and push if changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "data/atl_tsa_wait_times.csv"
          message: "chore: append TSA wait times [skip ci]"
          default_author: github_actions
